# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 568c76213a8af1e927823586cf852739a6952ea708cfb62df46d8d65c2c53cac8e34dccacfc101085d26638359ee9aeef45555c2c8664e1b46c9ed3908e12ebc

test:
  secret_key_base: 35cf877e37a2b22f51097451a3edb82d28dd705ecf97e33abe28ecee64d27c35979546e46433550d44fb90aef6a54de6d59f18c1aa9314b06137edb331bf44af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
